### ISSUE TITLE
howto use this package in meteor project? 

### ISSUE THREAD

**Issue by zevsuld** [em0ney/meteor-amcharts#1]
Hi there! I am trying to integrate amcharts in my Meteor project. I added package mrt:amcharts. 
I am trying to display it, but it is not appearing. I asked stackoverflow but no solution(http://stackoverflow.com/questions/26728854/howto-integrate-amcharts-in-meteorjs). Can you provide some example how to use it in meteor project please. I am trying this example (http://www.amcharts.com/demos/multiple-data-sets/). 
I will really appreciate if you provide some usage example. 
Thank you!

**Comment by Nullpo** [comment]
Hi @zevsuld , I'm with the same problem.... do you have any working example?

**Comment by em0ney** [comment]
Hi @zevsuld @Nullpo,

I'll create an example for you both and post it shortly.  In the meantime, take a look at http://www.amcharts.com/demos/donut-chart/ - should be able to copy the example code into your project to initialize a chart.

Elliott

**Comment by zevsuld** [comment]
Hi! @Nullpo actually I integrated amcharts for my project manually(I needed to integrate AmStock charts too). It works fine though. Back then I had very little experience with meteor and amcharts. This package actually very easy to use.

Hi! @em0ney That would be great. please add some examples. Also please up to date latest version of amcharts time to time. Amcharts updates pretty frequently. And it would be great if you make other amcharts library packages too, such as amstock chart, ampie chart etc..

**Comment by em0ney** [comment]
@Nullpo - I have created a [repo with example code](https://github.com/thesaucecode/meteor-amcharts-example) and a [demo site](http://em0ney-amcharts-example.meteor.com/).  I have also updated the [README](https://github.com/em0ney/meteor-amcharts) for this project.  Let me know if you need further help.

@zevsuld - I have the most recent amcharts integrated.  Pie charts and all other JS charts are available but I have not yet included the stock charts package which is a separate distribution from AmCharts..  Feel free to do this and submit a pull request, otherwise I'll get around to this soon.

**Comment by jonlachlan** [comment]
@em0ney I'm using this package and it works very well. It doesn't look like the Export feature works on any of the above demos. I am trying to get export working, do you have some ideas about how to get this working? I assume it has to do with the paths.

**Comment by jonlachlan** [comment]
I used your blog article to create my own package, and I was able to successfully use amChart's export plugin. Version 3.14.0 seems to have moved exports into /plugins folder, as well as added many features to the exports. 

Thanks so much for your very helpful resources!

**Comment by em0ney** [comment]
Thanks for the feedback @jonlachlan, I will create a new enhancement on this project to correct this on the public package and include new examples with working exports

**Comment by cynmihc2** [comment]
Hello em0ney, 
I can't get that when a chart is brought from the database by a user, this chart is showed in more than one browser at the same time. It works only for the browser where a user makes click but not for the others browsers. The user can bring the chart with a button. I think that this is related with reactivity and routing with iron router.  I have used ServerSession from the package matteodem:server-session for trying to show the chart but isnt work.

Can you help me please?

Thanks a lot.
