### ISSUE TITLE
update to latest version

### ISSUE THREAD

**Issue by chrisbutler** [em0ney/meteor-amcharts#2]
hey @em0ney, looks like the most recent version was released on a few weeks ago (http://www.amcharts.com/download/). I'd be glad to do a PR if you can merge and release a new version to atmosphere

**Comment by em0ney** [comment]
Hey @chrisbutler, Happy for you to do the PR.  If you don't have the time, I should be able to sort this out on the coming weekend.

Thanks mate!
Elliott
