### ISSUE TITLE
Convert this project to licensed version

### ISSUE THREAD

**Issue by res-io** [em0ney/meteor-amcharts#4]
Thanks for your work. I'm currently using this package in project.
I just bought the commercial version and I was wondering how to convert the existing project to the commercial one.
Any tips would be great!
Thanks!

Bye
Frederick

**Comment by em0ney** [comment]
Hey there @res-io,

At the moment, there is no such way, but I will get in contact with the amcharts core team and try to implement such a way to upgrade.

I'll be back to you with this ASAP.

Elliott

**Comment by res-io** [comment]
I’ve got the commercial files.
Could you explain me how to convert them into a package for Meteor?
If I could get your contact info, I would also compensate you for your time.

Thanks!

Frederick

**Comment by em0ney** [comment]
Hey @res-io,

I have been in contact with the AmCharts team.  Unfortunately, as they do not give a license key but instead a completely new distribution, there is no way to elegantly upgrade a client's package version to the commercial version.

But, I have written a blog post outlining how [you can create a private package](http://thesauceco.de/blog/Writing-Private-Meteor-Packages/)

If you need any more help, please get back in contact - and be sure to tell me whether this works for you!
